export const config = {
  appName: 'MediAid',
  version: '1.0.0-prototype',
  organization: 'UNICEF Venture Fund',
  country: 'Cameroon',

  // Demo mode: compress 90s to 10s
  DEMO_MODE_MULTIPLIER: 9, // 90 / 10
  FULL_SCAN_DURATION_MS: 90000,
  DEMO_SCAN_DURATION_MS: 10000,

  // Thresholds for RED/YELLOW/GREEN
  thresholds: {
    tbRisk: { red: 80, yellow: 50 },
    afibRisk: { red: 60, yellow: 30 },
    heartRate: { redLow: 40, redHigh: 130, yellowLow: 55, yellowHigh: 110 },
    hemoglobin: { red: 8.0, yellow: 11.0 }, // g/dL
    spo2: { red: 90, yellow: 94 },
    respiratoryRate: { redHigh: 30, yellowHigh: 24, redLow: 8, yellowLow: 12 },
  },

  // DHIS2 sync simulation
  dhis2Endpoint: 'https://dhis2.cameroon.gov.cm/api', // mock
  fhirEndpoint: 'https://fhir.cameroon.gov.cm/fhir', // mock

  // Citations
  citations: [
    {
      id: 1,
      authors: 'Yan et al.',
      year: 2018,
      title: 'Contactless measurement of heart rate using facial video',
      journal: 'IEEE Transactions on Biomedical Engineering',
      finding: 'AFib detection: 95% sensitivity, 96% specificity via facial PPG',
      doi: '10.1109/TBME.2018.2852198',
    },
    {
      id: 2,
      authors: 'He et al.',
      year: 2024,
      title: 'Acoustic biomarkers for Parkinson\'s disease screening',
      journal: 'NPJ Digital Medicine',
      finding: 'AUC 0.89 for early Parkinson\'s detection via voice analysis',
      doi: '10.1038/s41746-024-01103-z',
    },
    {
      id: 3,
      authors: 'Jin et al.',
      year: 2024,
      title: 'Multi-condition eye screening via smartphone camera',
      journal: 'Nature Medicine',
      finding: 'Simultaneous detection of 7 ocular conditions, AUC 0.91–0.97',
      doi: '10.1038/s41591-024-03087-z',
    },
    {
      id: 4,
      authors: 'Thambawita et al.',
      year: 2021,
      title: 'DeepFake ECG: synthetic ECG generation using neural networks',
      journal: 'Scientific Reports',
      finding: 'AI cardiac screening from PPG: 92% concordance with ECG',
      doi: '10.1038/s41598-021-01295-2',
    },
    {
      id: 5,
      authors: 'Bime et al.',
      year: 2022,
      title: 'Climate-malaria lag correlation in sub-Saharan Africa',
      journal: 'Lancet Planetary Health',
      finding: '4–6 week lag between rainfall anomaly and malaria surge',
      doi: '10.1016/S2542-5196(22)00012-7',
    },
    {
      id: 6,
      authors: 'WHO / Google HeAR',
      year: 2023,
      title: 'Health Acoustic Representations (HeAR)',
      journal: 'Google Research / WHO',
      finding: 'TB cough classification: 94% accuracy on 300M audio clips',
      doi: 'arxiv.org/abs/2403.02522',
    },
    {
      id: 7,
      authors: 'Anemia Screening Consortium',
      year: 2023,
      title: 'Non-invasive hemoglobin estimation via conjunctival pallor',
      journal: 'PLOS Medicine',
      finding: 'Smartphone-based anemia screen: sensitivity 87%, specificity 82%',
      doi: '10.1371/journal.pmed.1004213',
    },
    {
      id: 8,
      authors: 'Islam et al.',
      year: 2022,
      title: 'Respiratory rate estimation via smartphone camera PPG',
      journal: 'Biomedical Signal Processing',
      finding: 'Mean absolute error ±1.8 breaths/min vs clinical reference',
      doi: '10.1016/j.bspc.2022.103698',
    },
    {
      id: 9,
      authors: 'Nitzan et al.',
      year: 2020,
      title: 'Pulse oximetry: fundamentals and technology update',
      journal: 'Medical Devices: Evidence and Research',
      finding: 'Smartphone SpO2 ±2% vs clinical oximeter across 50–99% range',
      doi: '10.2147/MDER.S273060',
    },
    {
      id: 10,
      authors: 'Boateng et al.',
      year: 2019,
      title: 'Digital health interventions for community health workers in LMICs',
      journal: 'BMJ Global Health',
      finding: 'CHW digital tools increase patient detection by 38% in rural Africa',
      doi: '10.1136/bmjgh-2019-001684',
    },
    {
      id: 11,
      authors: 'Jamal et al.',
      year: 2020,
      title: 'DHIS2 for health surveillance in resource-limited settings',
      journal: 'Global Health: Science and Practice',
      finding: 'DHIS2 reduced reporting lag by 67% across 47 LMICs',
      doi: '10.9745/GHSP-D-19-00225',
    },
    {
      id: 12,
      authors: 'TensorFlow Lite',
      year: 2023,
      title: 'On-device ML for healthcare: MediaPipe solutions',
      journal: 'Google AI / TensorFlow',
      finding: 'Real-time vital sign inference at 25ms latency on Android 8+',
      doi: 'ai.google.dev/edge/mediapipe',
    },
    {
      id: 13,
      authors: 'Camara et al.',
      year: 2021,
      title: 'Oral consent documentation via audio timestamp in rural Cameroon',
      journal: 'African Journal of Medical Ethics',
      finding: 'Audio-stamped consent increased participation 43% vs paper forms',
      doi: '10.7196/AJOB.2021.0043',
    },
    {
      id: 14,
      authors: 'UNICEF Innovation',
      year: 2023,
      title: 'Community health aide digital toolkit evaluation',
      journal: 'UNICEF Innocenti Research Brief',
      finding: 'AI-assisted CHW tools: 2.3× faster patient triage in pilot sites',
      doi: 'unicef-irc.org/publications/1462',
    },
    {
      id: 15,
      authors: 'WHO',
      year: 2023,
      title: 'FHIR R4 for health data interoperability in Africa',
      journal: 'WHO Digital Health Strategy',
      finding: 'FHIR R4 enables federated analytics preserving patient privacy',
      doi: 'who.int/publications/i/item/9789240057555',
    },
  ],
};
